In [3]:
import numpy as np

In [6]:
sample_matrix=np.array(([1,4,6],[6,9,0],[4,1,6],[7,3,1]))
sample_matrix

array([[1, 4, 6],
       [6, 9, 0],
       [4, 1, 6],
       [7, 3, 1]])

In [7]:
sample_matrix[2][1]

1

In [8]:
sample_matrix[0,:]

array([1, 4, 6])

In [9]:
sample_matrix[0]

array([1, 4, 6])

In [10]:
sample_matrix[:,(1,2)]#all rows are considered in column 1 and 2

array([[4, 6],
       [9, 0],
       [1, 6],
       [3, 1]])

In [21]:
sample_array1=np.arange(0,10)
sample_array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
sample_array1+sample_array1


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [23]:
np.exp(sample_array1)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [24]:
np.sqrt(sample_array1)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [28]:
np.log(sample_array1)

C:\Users\digan\AppData\Local\Temp\ipykernel_10724\2737537472.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(sample_array1)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [29]:
np.square(sample_array1)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [31]:
np.std(sample_array1)

2.8722813232690143

In [32]:
np.var(sample_array1)

8.25

In [34]:
np.mean(sample_array1)

4.5

In [35]:
rand_matrix=np.random.randn(3,2)
rand_matrix

array([[ 0.14661625,  1.67332714],
       [ 2.60072625,  0.83505323],
       [-1.87763036, -1.73188718]])

In [36]:
np.round(rand_matrix,decimals=2)

array([[ 0.15,  1.67],
       [ 2.6 ,  0.84],
       [-1.88, -1.73]])

In [37]:
sports=np.array(["Football","Cricket","Hockey","Badminton","Cricket"])#U9 shows the  maximum number of letters in one word
np.unique(sports)

array(['Badminton', 'Cricket', 'Football', 'Hockey'], dtype='<U9')