In [1]:
import numpy as np


In [2]:
arr=np.array([2,4,1,3])
arr

array([2, 4, 1, 3])

In [4]:
list_of_lists=[[1,2,3],[4,5,6],[7,8,9]]
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
np.arange(1,15)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [7]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [8]:
np.arange(1,46,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41])

In [9]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [10]:
np.zeros(5,int)


array([0, 0, 0, 0, 0])

In [11]:
np.zeros(4,dtype=int)

array([0, 0, 0, 0])

In [15]:
np.ones((2,5),int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [18]:
np.linspace(2,15,4)#divides the range in 4 equal parts

array([ 2.        ,  6.33333333, 10.66666667, 15.        ])

In [19]:
np.linspace(0,5)#if 3rd term is nit mentioned it is by default =50

array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

In [25]:
np.linspace(0,4,2)


array([0., 4.])

In [26]:
np.random.rand(3,2)#3 rows 2 columns and random number is between 0 to 1

array([[0.03414475, 0.82008463],
       [0.63169455, 0.5396945 ],
       [0.12858368, 0.59387607]])

In [24]:
np.random.randn(3,3)#gives negative numbers as well

array([[ 1.35302591,  0.04813895,  0.6918598 ],
       [ 1.41277989, -1.60907092, -1.22637232],
       [-0.00755251,  0.642183  ,  0.54333804]])

In [27]:
np.random.randint(34,100)#gives a random number between 34 to 100 not including 100

57

In [28]:
np.random.randint(24,50,100)

array([49, 38, 25, 36, 28, 46, 44, 48, 40, 48, 46, 35, 41, 27, 26, 30, 46,
       34, 28, 41, 40, 26, 25, 26, 37, 43, 45, 43, 30, 48, 34, 28, 26, 31,
       37, 24, 33, 29, 36, 30, 49, 28, 43, 27, 39, 37, 41, 40, 44, 45, 46,
       28, 37, 33, 33, 48, 41, 46, 32, 40, 27, 25, 42, 25, 49, 41, 33, 45,
       43, 27, 40, 40, 41, 29, 37, 31, 30, 34, 48, 46, 41, 27, 30, 24, 28,
       45, 35, 29, 29, 36, 49, 30, 25, 37, 25, 39, 36, 42, 42, 49])

In [29]:
sample_array=np.arange(30)
sample_array.reshape(5,6)


array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [32]:
sample_array.reshape(2,7)


ValueError: cannot reshape array of size 30 into shape (2,7)

In [34]:
rand_array=np.random.randint(20,50,10)
rand_array

array([48, 46, 41, 43, 37, 26, 30, 28, 27, 43])

In [35]:
rand_array.min()

26

In [36]:
rand_array.argmin()#returns the index of min

5

In [38]:
rand_array.max()

48

In [39]:
rand_array.argmax()

0

In [40]:
type(sample_array)

numpy.ndarray

In [41]:
sample_array.dtype

dtype('int32')

In [42]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [45]:
a=np.random.rand(3,2)
a

array([[0.95093339, 0.68891317],
       [0.60122477, 0.7256724 ],
       [0.41488557, 0.49964971]])

In [46]:
a.T#transpose

array([[0.95093339, 0.60122477, 0.41488557],
       [0.68891317, 0.7256724 , 0.49964971]])

In [47]:
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [48]:
sample_array[3:7]#starts from index 3 and ends at index 7-1=6

array([3, 4, 5, 6])

In [50]:
sample_array[1:4]=100
sample_array

array([  0, 100, 100, 100,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29])

In [51]:
sample_array[:]=1000
sample_array

array([1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000,
       1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000,
       1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000])